---
#  "app_id" is a fk and needs to discussed and is not in body of post call
- name: Insert into DB V_CHECKLIST_STATUS
  block:
  - name: POST to V_CHECKLIST_STATUS
    uri:
      url:  "{{ apex_url }}/{{ apex_uri }}/checklist/checklist_status"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: POST
      body_format: json
      body: ""
      headers:
        Content-Type: "application/json"
        Cache-Control: "no-cache"
        record_type: "message"
        task_area: "{{ task_area }}"
        task_id: "{{ task_id }}"
        task_key: "{{ task_key }}"
        task_status: "{{ task_status }}"
        task_message: "{{ task_message }}"
        platform_vendor: "{{ platform_vendor }}"
        standard_task_id: "{{ standard_task_id }}"
    register: checklist_status_response

  rescue:
  - name: Store the Json If APEX Server Is Down
    delegate_to: localhost
    become: False
    lineinfile:
      path: "{{ json_backup_dir }}/{{ task_id }}_checklist_name.json"
      line: "{{ checklist_body  | to_json }}"
      create: yes
    when:
    - checklist_status_response == "500" or  checklist_status_response.status == -1
