---
- name: insert new checklist entry
  include_tasks: db_patch_checklist_insertion.yml
  when: chklst_json_body.new_entry

- debug:
    var: chklst_json_body
    
- debug:
    msg: "{{ apex_url }}/{{ apex_uri }}/patching/dbpatchhistory/{{ checklist_id }}"  
    
- name: Checklist Update
  block:
    - name: update the json data using PUT call
      uri:
        url:   "{{ apex_url }}/{{ apex_uri }}/patching/dbpatchhistory/{{ checklist_id }}"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: PUT
        body_format: json
        body:  "{{ chklst_json_body }}"
        register: checklist_update_response
        headers:
          Content-Type: "application/json"
      when: chklst_json_body.new_entry == False
  rescue:
    - name: Store the Json If APEX Server Is Down
      delegate_to: localhost
      become: no
      lineinfile:
        path: "{{ json_backup_dir }}/{{ oracle_db_name }}_patch_chklst_updates.json"
        line: '{
                  "host_name": "{{ ansible_hostname }}",
                  "id": "{{ checklist_id }}",
                  "update": {{ chklst_json_body | to_json }} 
                }'
        create: yes
