SET SERVEROUTPUT ON
SET DEFINE OFF
SPOOL /u01/tmp/postval/post_provisioning_sql_result.lst append;
CREATE PROFILE USER_ACCOUNT_PROFILE
LIMIT
PASSWORD_GRACE_TIME 7
PASSWORD_LIFE_TIME 90
PASSWORD_REUSE_TIME 360
PASSWORD_REUSE_MAX UNLIMITED
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION F_PWD_VERIFY_COMPLEXITY;

CREATE PROFILE APP_ACCOUNT_PROFILE
LIMIT
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME 7
PASSWORD_REUSE_MAX UNLIMITED
FAILED_LOGIN_ATTEMPTS 10
PASSWORD_LOCK_TIME 1
PASSWORD_VERIFY_FUNCTION F_PWD_VERIFY_COMPLEXITY;
SPOOL OFF;
SET DEFINE ON
SET SERVEROUTPUT OFF
EXIT
